# Input-output sets and source mappings.
# The detailed SUT leaf list is static. The model resolution is generated by
# IndustryResolutionData.jl and read here by all subsequent refresh modules.
module InputOutputSettings

using CSV
using DataFrames

const input_output_data_dir = joinpath(@__DIR__, "..", "data", "input_output")
const industry_resolution_dir = joinpath(@__DIR__, "..", "data", "industry_resolution")
const industry_resolution_file = joinpath(industry_resolution_dir, "industry_resolution.csv")
const industry_coverage_file = joinpath(industry_resolution_dir, "industry_resolution_coverage.csv")

const eurostat_supply_dataset = "naio_10_cp15"
const eurostat_use_dataset = "naio_10_cp1610"
const eurostat_margin_dataset = "naio_10_cp1620"
const eurostat_net_product_tax_dataset = "naio_10_cp1630"
const eurostat_unit = "MIO_EUR"
const cell_tolerance = 1e-6

# Eurostat's standard SUT detail is A*64 for NACE industries and P*64 for CPA
# products. The national SUT tables split real estate into L68A and L68B.
const sut_detail_codes = [
  "A01", "A02", "A03", "B", "C10-12", "C13-15", "C16", "C17", "C18", "C19",
  "C20", "C21", "C22", "C23", "C24", "C25", "C26", "C27", "C28", "C29",
  "C30", "C31_32", "C33", "D", "E36", "E37-39", "F", "G45", "G46", "G47",
  "H49", "H50", "H51", "H52", "H53", "I", "J58", "J59_60", "J61", "J62_63",
  "K64", "K65", "K66", "L68A", "L68B", "M69_70", "M71", "M72", "M73",
  "M74_75", "N77", "N78", "N79", "N80-82", "O", "P", "Q86", "Q87_88",
  "R90-92", "R93", "S94", "S95", "S96", "T", "U",
]

const fallback_product = [Symbol(string(c)) for c in 'A':'U']
const fallback_section_to_industry = Dict(section => Symbol("i$section") for section in fallback_product)

"""Read the generated common resolution, or use A21 only while the resolver itself is running."""
function load_resolution()
  if isfile(industry_resolution_file)
    df = CSV.read(industry_resolution_file, DataFrame)
    @assert nrow(df) > 0 "Industry resolution file is empty: $industry_resolution_file"
    return df
  end
  return DataFrame(
    industry = [fallback_section_to_industry[s] for s in fallback_product],
    product = fallback_product,
    eurostat_group = string.(fallback_product),
    members = string.(fallback_product),
    member_count = ones(Int, length(fallback_product)),
    first_leaf = collect(1:length(fallback_product)),
    last_leaf = collect(1:length(fallback_product)),
  )
end

const resolution = load_resolution()
const product = [Symbol(string(x)) for x in resolution.product]
const source_industry = [Symbol(string(x)) for x in resolution.industry]
@assert length(product) == length(source_industry) "Products and industries must use the same common resolution"
@assert allunique(product) && allunique(source_industry) "Common industry/product labels must be unique"

# Member information is used for model assumptions that remain section based.
const product_members = Dict(Symbol(string(row.product)) => split(string(row.members), ';') for row in eachrow(resolution))
const industry_members = Dict(Symbol(string(row.industry)) => split(string(row.members), ';') for row in eachrow(resolution))
member_section(code::AbstractString) = Symbol(first(code))
const product_sections = Dict(p => Set(member_section.(members)) for (p, members) in product_members)
const industry_sections = Dict(i => Set(member_section.(members)) for (i, members) in industry_members)

products_in_sections(sections) = [p for p in product if !isempty(product_sections[p]) && product_sections[p] ⊆ Set(Symbol(string(s)) for s in sections)]
industries_in_sections(sections) = [i for i in source_industry if !isempty(industry_sections[i]) && industry_sections[i] ⊆ Set(Symbol(string(s)) for s in sections)]

# Wholesale/retail trade and transport supply the margin services. At detailed
# resolution this expands from G/H to all selected products wholly inside G/H.
const margin_services = products_in_sections([:G, :H])
@assert !isempty(margin_services) "The selected resolution must contain G/H margin-service products"

const final_uses = [:C, :G, :X, :K, :INV]
const origin = [:domestic, :import]
const final_use_rename = Dict(
  "P3_S14" => :C,
  "P3_S15" => :C,
  "P3_S13" => :G,
  "P51G" => :K,
  "P5M" => :INV,
  "P6" => :X,
)

"""Choose a non-overlapping set of source codes that exactly tiles one model group.
Prefer the finest available tiling so aggregate and detailed rows are never double counted."""
function tile_source_codes(rows::DataFrame, first_leaf::Int, last_leaf::Int)
  by_first = Dict{Int,Vector{Tuple{Int,String}}}()
  for row in eachrow(rows)
    a, b = Int(row.first_leaf), Int(row.last_leaf)
    first_leaf <= a <= b <= last_leaf || continue
    push!(get!(by_first, a, Tuple{Int,String}[]), (b, string(row.source_code)))
  end
  best = Dict{Int,Union{Nothing,Vector{String}}}(last_leaf + 1 => String[])
  for pos in last_leaf:-1:first_leaf
    choices = Vector{String}[]
    for (b, code) in get(by_first, pos, Tuple{Int,String}[])
      tail = get(best, b + 1, nothing)
      isnothing(tail) || push!(choices, [code; tail])
    end
    best[pos] = isempty(choices) ? nothing : choices[argmax(length.(choices))]
  end
  result = get(best, first_leaf, nothing)
  @assert !isnothing(result) "Source coverage cannot tile model leaves $first_leaf:$last_leaf"
  return result
end

"""Return raw Eurostat source-code => model-label mapping for a tested source slice.
The coverage file is written by IndustryResolutionData before the remaining refresh steps."""
function source_mapping(source_name::AbstractString, target::Symbol)
  @assert target in (:industry, :product)
  @assert isfile(industry_coverage_file) "Run IndustryResolutionData.refresh_industry_resolution!() before loading model data"
  coverage = CSV.read(industry_coverage_file, DataFrame)
  rows = coverage[coverage.source .== source_name, :]
  @assert nrow(rows) > 0 "No coverage rows found for source slice $source_name"
  mapping = Dict{String,Symbol}()
  for row in eachrow(resolution)
    model_label = target == :industry ? Symbol(string(row.industry)) : Symbol(string(row.product))
    for code in tile_source_codes(rows, Int(row.first_leaf), Int(row.last_leaf))
      @assert !haskey(mapping, code) || mapping[code] == model_label "Source code $code maps to multiple model groups"
      mapping[code] = model_label
    end
  end
  return mapping
end

# Backward-compatible section helpers for modules/assumptions that genuinely
# refer to a whole NACE/CPA section rather than to the data resolution.
const section_to_industries = Dict(s => industries_in_sections([s]) for s in fallback_product)
const section_to_products = Dict(s => products_in_sections([s]) for s in fallback_product)

end # module
